# manually run via pre-commit run --all-files
# alternatively, pre-commit run <hook_id> to run a specific hook
default_language_version:
  python: python3.8
minimum_pre_commit_version: 2.9.2

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

# run tests
- repo: local
  hooks:
    # formatting
    - id: black
      name: formatting (black)
      entry: black .
      stages: [push]
      language: system
    # tests
    - id: tests
      name: run tests
      entry: green -vvv --run-coverage
      language: system
      types: [python]
      stages: [push]
    # typehints
    # - id: mypy
    #   name: typehints (mypy)
    #   entry: mypy -v --exclude "setup\.(py|cfg)|(build|misc|bin|\.github)/$" .
    #   language: system
    #   #stages: [push]